<?php

// config for Fynduck/FilesUpload
return [
    /*
     * Default disk used when none is set explicitly on the uploader.
     */
    'disk' => 'public',

    /*
     * Run the image optimizer by default.
     */
    'optimize' => true,

    /*
     * Default encode quality (0-100).
     */
    'quality' => 90,

    /*
     * Background size generation.
     *
     * When enabled (or when ->queue() is called on the uploader), size variants are
     * generated by queue workers instead of on the request thread, so the client does
     * not wait for every size to be resized and optimised.
     */
    'queue' => [
        // Generate sizes in the background by default. Opt-in keeps full BC.
        'enabled' => false,

        // Queue connection (null = default connection).
        'connection' => null,

        // Queue name (null = default queue).
        'queue' => null,

        // true  = one job per size, fanned out as a batch (parallel across workers).
        // false = a single job that renders every size serially.
        'per_size' => true,
    ],
];
